      <footer>
        <div class="container py-2 text-center">
          <div class="row no-gutters justify-content-between">
            <div class="col">
              <a href="#">About</a>
            </div>
            <div class="col">
              <a href="#">Posts</a>
            </div>
            <div class="col">
              <a href="#">Account</a>
            </div>
            <div class="col">
              <a href="#">Contact</a>
            </div>
          </div>
          <span>2019 dkdev</span>
        </div>
      </footer>
      <div class="overlay"></div>
    </div>
    <script src="<?php echo PUBROOT; ?>/js/jquery.js"></script>
    <script type="text/javascript" src="<?php echo PUBROOT; ?>/js/script.js"></script>
  </body>
</html>
