<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="<?php echo URLROOT; ?>pub/css/styles.css">
    <link rel="stylesheet" href="<?php echo URLROOT; ?>pub/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo URLROOT; ?>pub/css/fontawesome.min.css">
    <title><?php echo SITENAME; ?></title>
  </head>
  <body>
    <div class="page-wrapper">
      <?php require APPROOT . '/views/inc/navbar.phtml' ?>
