<header>
  <div class="container">
    <div class="row mb-2 py-2 text-uppercase no-gutters justify-content-between">
      <div class="col-3">
        <span id="menu-toggler" class="menu-toggler" href="#">
          <img src="<?php echo URLROOT; ?>pub/img/more.svg" height="24px" alt="">
        </span>
      </div>
      <div class="col-6 text-center">
        <a href="<?php echo URLROOT; ?>">
          <img src="<?php echo URLROOT; ?>pub/img/logo.svg" height="26px" alt="">
        </a>
      </div>
      <div class="col-3 text-right">
        <a class="mr-2" href="
          <?php
            if(isset($_SESSION['user_id'])) :
              echo URLROOT . 'posts';
              else : echo URLROOT . 'users/login';
            endif;
          ?>">
          <img src="<?php echo URLROOT; ?>pub/img/user.svg" alt="">
        </a>
        <a href="<?php echo URLROOT; ?>">
          <img src="<?php echo URLROOT; ?>pub/img/search.svg" alt="">
        </a>
      </div>
      <div id="nav-menu" class="nav-menu p-3 text-uppercase">
        <ul class="list-unstyled">
          <?php if(isset($_SESSION['user_id'])) : ?>
          <li>
            <span>Hi, <?php echo $_SESSION['user_name']; ?></span>
          </li>
          <li>
            <a href="<?php echo URLROOT; ?>users/logout">Logout</a>
          </li>
          <?php else : ?>
          <li>
            <a href="<?php echo URLROOT; ?>users/register">Create an account</span></a>
          </li>
          <li>
            <a href="<?php echo URLROOT; ?>users/login">Login</a>
          </li>
          <?php endif; ?>
          <li><a href="<?php echo URLROOT; ?>posts">posts</a></li>
        </ul>
      </div>
    </div>
  </div>
</header>
